# Generated by Django 3.1 on 2024-04-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinos_app', '0002_clientreview_contactmodel_projectmodel_teammodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
