# Generated by Django 3.1 on 2024-04-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinos_app', '0007_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_heading', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False, help_text='0-default,1-Hidden')),
            ],
        ),
    ]
