# Generated by Django 3.1 on 2024-04-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinos_app', '0008_team_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=1000, null=True)),
                ('team_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.BooleanField(default=False, help_text='0-default,1-Hidden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinos_app.team_category')),
            ],
        ),
    ]
