# Generated by Django 3.2.10 on 2024-04-09 04:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinos_app', '0011_auto_20240406_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career_model',
            name='job_details',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
