# Generated by Django 3.2.10 on 2024-04-09 05:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinos_app', '0012_alter_career_model_job_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career_model',
            name='job_requirements',
        ),
        migrations.RemoveField(
            model_name='career_model',
            name='job_responsibilities',
        ),
        migrations.RemoveField(
            model_name='career_model',
            name='skills_experience',
        ),
        migrations.AlterField(
            model_name='career_model',
            name='job_details',
            field=ckeditor.fields.RichTextField(max_length=20000),
        ),
    ]
