# Generated by Django 3.2.10 on 2024-04-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinos_app', '0014_youtubevideo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YouTubeVideo',
            new_name='DroneDevelopment',
        ),
    ]
