# Generated by Django 3.1 on 2024-04-09 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinos_app', '0018_auto_20240409_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_description', models.TextField(blank=True, null=True)),
                ('sub_heading', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_description', models.TextField(blank=True, null=True)),
                ('skills_experience', models.TextField(blank=True, null=True)),
                ('blog_image', models.ImageField(upload_to='images/')),
                ('status', models.BooleanField(default=False, help_text='0-default,1-Hidden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinos_app.blog_category')),
            ],
        ),
    ]
