# Generated by Django 3.1 on 2024-04-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinos_app', '0020_androiddevelopment_artificialintelligence_automation_crmdevelopment_dataanalysis_erpdevelopment_flan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ui_UxModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
