# Generated by Django 5.0.4 on 2024-04-22 18:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinos_app', '0022_auto_20240412_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_logo',
            name='logo',
            field=models.ImageField(upload_to='team_images/'),
        ),
        migrations.AlterField(
            model_name='client_logo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expertised_technologies',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='team_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expertised_technologies',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
