# Generated by Django 5.0.4 on 2024-04-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinos_app', '0024_service_category_alter_blog_details_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone_development', models.URLField(unique=True)),
                ('cyber_security', models.URLField(unique=True)),
                ('software_development', models.URLField(unique=True)),
                ('data_analysis', models.URLField(unique=True)),
                ('web_development', models.URLField(unique=True)),
                ('android_application', models.URLField(unique=True)),
                ('ios_application', models.URLField(unique=True)),
                ('erp_development', models.URLField(unique=True)),
                ('crm_development', models.URLField(unique=True)),
                ('artificial_intelligence', models.URLField(unique=True)),
                ('flange_management', models.URLField(unique=True)),
                ('robotics', models.URLField(unique=True)),
                ('automation', models.URLField(unique=True)),
                ('ui_ux', models.URLField(unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
