# Generated by Django 5.0.4 on 2024-04-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinos_app', '0025_youtube_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AndroidDevelopment',
        ),
        migrations.DeleteModel(
            name='ArtificialIntelligence',
        ),
        migrations.DeleteModel(
            name='Automation',
        ),
        migrations.DeleteModel(
            name='CrmDevelopment',
        ),
        migrations.DeleteModel(
            name='CyberSecurity',
        ),
        migrations.DeleteModel(
            name='DataAnalysis',
        ),
        migrations.DeleteModel(
            name='DroneDevelopment',
        ),
        migrations.DeleteModel(
            name='ErpDevelopment',
        ),
        migrations.DeleteModel(
            name='FlangeManagement',
        ),
        migrations.DeleteModel(
            name='IosDevelopment',
        ),
        migrations.DeleteModel(
            name='Robotics',
        ),
        migrations.DeleteModel(
            name='Service_Category',
        ),
        migrations.DeleteModel(
            name='SoftwareDevelopment',
        ),
        migrations.DeleteModel(
            name='Ui_UxModel',
        ),
        migrations.DeleteModel(
            name='WebDevelopment',
        ),
    ]
