# Generated by Django 5.0.4 on 2024-04-23 10:02

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinos_app', '0026_delete_androiddevelopment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_details',
            name='skills_experience',
        ),
        migrations.RemoveField(
            model_name='blog_details',
            name='sub_description',
        ),
        migrations.RemoveField(
            model_name='blog_details',
            name='sub_heading',
        ),
        migrations.AlterField(
            model_name='blog_details',
            name='blog_description',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, max_length=60000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog_details',
            name='blog_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
