# Generated by Django 5.0.4 on 2024-04-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinos_app', '0027_remove_blog_details_skills_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_video',
            name='android_application',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='youtube_video',
            name='artificial_intelligence',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='youtube_video',
            name='automation',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='youtube_video',
            name='crm_development',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='youtube_video',
            name='cyber_security',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='youtube_video',
            name='data_analysis',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='youtube_video',
            name='drone_development',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='youtube_video',
            name='erp_development',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='youtube_video',
            name='flange_management',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='youtube_video',
            name='ios_application',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='youtube_video',
            name='robotics',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='youtube_video',
            name='software_development',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='youtube_video',
            name='ui_ux',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='youtube_video',
            name='web_development',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
