# Generated by Django 5.0.4 on 2024-04-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinos_app', '0028_alter_youtube_video_android_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
