# Generated by Django 5.0.4 on 2024-04-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinos_app', '0029_service_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Youtube_video',
        ),
    ]
