# Generated by Django 5.0.4 on 2024-04-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinos_app', '0031_alter_candidate_email_alter_candidate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='tinos_app.career_model'),
        ),
    ]
