# Generated by Django 5.0.6 on 2024-12-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinos_app', '0032_candidate_job_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('event_video', models.FileField(blank=True, null=True, upload_to='event_videos/')),
            ],
        ),
    ]
